### ISSUE TITLE
[W6-api-sentiment-project] Pablo FR

### ISSUE THREAD

**Issue by fromeropablo** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#1]
https://github.com/fromeropablo/Project-week-06

**Comment by AnaAGG** [comment]
# 😀☹️ api-sentiment-project 😀☹️

Holaaaaa Pablooooo 🙋‍♀️, vamos con el proyecto de crear una API!!

## Readme
 
 Vamos con el readme! La verdad es que no te dejaste mucho los sesos en esta parte... Haces una pequeña introducción del proyecto, pusiste las librerías que has usado con los links y el link de donde te descargaste los datos. Sin embargo, me han faltado algunas cositas. Te dejo por aquí unos cuantos comentarios por si te aportan valor en el futuro:

- Hubiera estado bien que pusieras algunos ejemplos de tus endpoints: 

        Some examples of API calls:
        To read all the phrases of a given character

        sentencias = ("http://0.0.0.0:5000/sentencias/IDPERSONAJE")

        Returns: 
        [{'sentencia': 'bla bla bla'},
        {'sentencia': 'bla bla bla'},
        {'sentecia': 'bla bla bla'}]


- Pablo... has dejado hasta frases a medias!     
        
        "We are gonna do a sentiment analysis to..." y que más?? 

## Estructura del repositorio
 
En general la estructura del repo esta bien, no se te ha colado ningún archivo "rarinchi" fuera del `.gitignore`,tienes todo muy bien compartimentado en distintas carpertas. Solo como detalle:

- El jupyter que tienes por ahí suelto, puedes meterlo en una carpeta que se llame Notebooks. En este caso, que solo tienes uno no es tan importante, pero si tienes varios puede ayudar mucho. Y además si lo puedes numerar quedan perfectos. 

## Sintaxis de código

Pues de código tengo poco que decirte, lo que tienes en general esta bien. 

- Te faltan los *docstrings* en las funciones. 

- Tienes funciones a medias... Entiendo que lo que querías hacer es el *sentimental analysis* a continuación de la query:

    ```python
    def episodio(season, episode):
        query = f"""
        SELECT character_name, line, season, episode
        FROM south_park
        WHERE episode = "{episode}", season = "{season}"
        """
    # luego puedes convertir esta query a dataframe y con ese dataframe ya haces el análisis de sentimientos con las funciones que tienes  du en el otro .py
    ```

## ToDo
Bueno Pablo, las APIs pueden ser un poco dolorosas al principio y poco motivantes pero te has creado tu propia API 👏🏽. Te dejo por aquí algunas cosas que se me han ido ocurriendo segun leía tu proyecto: 

- Dale una vuelta a ese readme, por lo menos termina la frase!

- Podrías hacer algún endpoint más, sobre todo en la parte de `POST`, como uno para eliminar frases o actualizar. Que el usuario pueda alimentar tu base de datos. 

- Por la parte del post, podrías crearte otros endpoints como las frases por personaje y temporada. 

- Tenías algunas funciones incompletas, dale una vuelta a esas funciones para que no te queden así. 

En cualquier caso Pablo, te has creado tu BBDD en SQL, te has creado  *enpoints* (tanto GET como POST 👏🏽), has hecho una representación gráfica de tus datos 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/118390104-a8ff0180-b62d-11eb-9665-a7f3cfd2e1c0.png)
