### ISSUE TITLE
[W6-api-sentiment-project] Javier Cabrera

### ISSUE THREAD

**Issue by Javi-Python** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#10]

**Comment by Javi-Python** [comment]
https://github.com/Javi-Python/API-Project.git

**Comment by AnaAGG** [comment]
# 💰 api-sentiment-project 💰

Holaaaaa Javi 🙋‍♀️, vamos con el proyecto de crear una API!! 🔥🔥

## Readme

Vamos a por el readme, en general esta bien, empiezas haciendo una pequeña intro de lo que la gente se encontrará en tu API, super bien. Tienes muy bien dividido los métodos `get` y los  `post`👏🏽, y cada uno de ellos explicando suuper bien lo que nos va a devolver. A modo de detalles:
- Cuando haces la descripción de los *endpoints* me ha faltado un ejemplo de lo que no devuelve cada uno de ellos. 

- Acuérdate de las librerías que has usado para este proyecto. 


## Estructura del repositorio

A groso modo la organización esta bien, aunque has tenido trabajos mejores en cuanto a organización. Te dejo por aquí algunas cosillas que he ido viendo: 

- Tienes ficheros `.csv` que entiendo que son datos fuera de la carpeta de `data`

- Se te han escapado algunos archivos temporales fuera del `.gitignore` 

- Tienes docstrings en algunas funciones y en otras no. Intenta unificarlo. 

- La carpeta `pics` guardas todas las imágenes que has ido creando durante el proyecto lo cual esta perfecto! Esto es más un detalle, pero intenta ponerle un nombre más general, como "images" o "figures". Algo que la gente lo lea sepa lo que hay en esa carpeta. 

- Tienes 3 jupyters, sería perfecto si los metieras en una carpeta y si ya los numeras para saber el orden de trabajo quedaría perfecto! 

- Esos prints infinitos en algunos jupyter Javi!!

- Mezclas español e inglés a lo largo del repo. El readme en inglés, pero los docstring de las funciones en español. Intenta unificar eso va? 

- La carpeta que tienes como `tools` la puedes llamar `src` ya que es donde tienes todos tus archivos `.py`. 

Parecen muchas cosas pero en realidad son detalles, esta genial Javi!!!!!

## Sintaxis de código

Buen trabajo de código Javi, tienes funciones cortitas con objetivos específicos, suuper bien 🔝. En realidad tengo poco que decirte de esta parte 👏🏽👏🏽

- En el archivo `getredditdata.py` tienes la función `from_reddit`. La función esta perfecta, solo como detalle, creo que tienes unas líneas de código que no te hacen falta. Como por ejmplo la de pd.DataFrame. Para que la añades si en ningún momento trabajas con dataframes?
    ```python
    def from_reddit(subreddit, limit):
        client_id = os.getenv('client_id')
        secret = os.getenv('secret')
        user = os.getenv('user')
        dotenv.load_dotenv()
        reddit = praw.Reddit(client_id=client_id, client_secret= secret, user_agent= user)
        hot_posts = reddit.subreddit(f'{subreddit}').top('month', limit=limit)
        df = pd.DataFrame(columns = ['created', 'id', 'title', 'upvotes', 'num_comments', 'comment_body'])
        lista = []
        for post in hot_posts:
            lista.append({ 'created': post.created_utc, 'id': post.id, 'title': post.title, 'upvotes': post.score, 'num_comments': post.num_comments,
                        'comment_body': [comment.body for comment in post.comments if (hasattr(comment, "body") and comment.distinguished==None)][0]})
        return lista
    ```

- En el *endpoint* donde devuelves el número de *tickers* en cada título del post si te fijas te esta devolviendo `NaN` y `None`. Si no lo estoy entendiendo mal, esa información no sería útil para los usuarios de la API. Podrías hacer dos cosas:
    - Limpiar los datos antes de meterlos en tu base de datos, evitando meter datos nulos
    - Limpiar la respuesta de la query de mongo dentro del propio *endpoint*. 

## ToDo

Tienes una base de datos muy buena para poder hacer más "data" en tu API. Algunas ideas que me vienen a la cabeza viendo tu datos son:

- Con la columna de `datetime`, en este caso solo tienes un mes, pero si metes más meses podrías comparar entre épocas del año (primvera *vs* invierno) o entre momentos clave(covid, algunas elecciones...)

- Ver si hay algún tipo de relación entre las columnas de `upvotes`	y `num_comments`

- Crear un *endpoint* donde un usuario pueda dar el `id` y se le devuelva su análisis de sentimientos

Por otra parte, en cuanto a detalles más específicos: 

- Los docstrings en todas las funciones, que las personas que vengan a ver tu repo se lo encuentre todo ready ready. 

- Puedes meter algo más de visualización y más datos, eso le aportará muchísimo valor a tu API. 

En cualquier caso Javi, te has creado una API desde cero. Has hecho requests a otra API para sacar tus datos, los has metido en mongo y te has creado múltiples *endpoints*. Las APIs al principio pueden resultar algo dolorosas pero lo has hecho genial!!! 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/117124652-e72c3380-ad98-11eb-8b9e-37edb2a83592.png)
