### ISSUE TITLE
[W6-api-sentiment-project] Unai Arteaga 

### ISSUE THREAD

**Issue by Unaiat** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#11]
https://github.com/Unaiat/Sentiment_analysis_project

**Comment by AnaAGG** [comment]
#  ![img](http://www.gomotes.com/emoticon/santaslittlehelper.gif) api-sentiment-project ![img](http://www.gomotes.com/emoticon/santaslittlehelper.gif)

Holaaaaa Unai 🙋‍♀️, vamos con el proyecto de crear una API!! 🔥🔥

## Readme

Suuuper bien el Readme Unai, esta super explicado todo, con el link para descargar el dataset de kaggle y la descripción de cada uno de los endpoints, las librerías que has usado etc. 
Te dejo por aquí unos detalles por si te aportan valor:

- Las librerías, si pones los links a la documentación oficial te quedaría perfecto! 

- Sobre los endpoints, has indicado todos tus endpoints y lo que hace cada uno, podrías poner algún ejemplo de cómo hacer una petición. Por ejemplo:

        Some examples of API calls:
        To read all the phrases of a given character

        phrases = ("http://0.0.0.0:5000/phrases/Homer Simpson")

        Returns: 
        [{'phrases': 'But... but...'},
        {'phrases': 'Revue...'},
        {'phrases': 'Go, go make magic. You just go.'}]

- Por ponerme tiquismiquis, has añadido un par de imágenes al final del readme, no se renderizaron bien 😔. Hay que mirar que paso ahí


## Estructura del repositorio

La estructura del repo esta perfecta Unai! Te dejo un par de detalles que ví, pero como te digo son detalles muy finos: 

- Se te ha colado algún archivo temporal fuera del `.gitignore`

- Tienes tres jupyters con todo el proceso de trabajo lo cual está perfecto. Los puedes meter en una carpeta para que no estén sueltos por ahí, si además los numeras te quedaría perfecto!!  

- Lo has hecho con SQL lo cual esta perfecto, como tienes 2 tablas hubiera estado perfecto que añadieras un esquema de cómo esta diseñada tu BBDD. 

- Suuuper bien todas las funciones con sus docstrings 👏🏽

## Sintaxis de código

Lo primerito de todo, genial que te animaras con SQL! Estamos menos familiarizados con este tipo de BBDD y seguro que fue un reto 👏🏽

Sobre el código tengo poco que decirte, esta todo super claro Unai. Hiciste muchas funciones con objetivos específicos y todas super bien documentadas. 

Leyendo tu código me han surgido algunas dudas sobre la API:

- En el proceso de limpieza del dataframe, te has creado unas cuantas funciones de limpieza, suuuper bien! Solo como detalle o "reto" para la próxima vez, cuando usas la función `replace` que te creaste la llamas dos veces para limpiar dos columnas diferentes pero con las mismas cosas que reemplazar. Recuerda qué tenemos los `kwargs` y `args` que nos permiten pasar un número indefinido de parámetros a una función. Te dejo por aquí algo de [docu](https://book.pythontips.com/en/latest/args_and_kwargs.html)

    ```python
    cle.replace(simpsons_phrases, 'raw_character_text', r"[\"]", r"'")
    # en este caso le puedes pasar una lista con las columnas que quieres modificar
    ```

- Cuando te creas las tablas de SQL si ya te creas unas funciones para el proceso e SQL lo clavas! 😉

- Cuando haces el método post para insertar nuevos datos en tu BBDD, dada la estructura de tu API, ¿tiene sentido insertar solo un personaje sin frase? Podrías:

    - Crearte un único *endpoint* donde se inserte a la vez el personaje en la tabla de personajes y el personaje y su frase en la tabla de frases. 

        ```python
        def insert_character(name):
        engine.execute(f"""
        INSERT IGNORE INTO characters (name) VALUES
        ('{name}');
        """
        )
        return get.get_name(name)

        def insert_phrase(episode_id, character_id, phrase):
            engine.execute(f"""
            INSERT INTO phrases (episode_id, character_id, phrase) VALUES
            ({episode_id}, {character_id}, '{phrase}');               
            """
            )
            return "The info has been added to the database"
        # si te creas un único endpoint lo mismo puedes reducir estas funciones a una sola
        ```

## ToDo

Bueno Unai, la verdad es que tienes un proyecto bastante completo, como posibles ideas para el futuro, podrias: 

- Incluir el sentimental análisis en un endpoint de tu API. 

- Hacer un endpoint que te diera el *sentimental analysis* para un personaje dado, y puedes sacar ese sentimental por temporada. O puedes evaluar si a lo largo de las temporadas el lenguaje de la serie va cambiando. 

- Te animo a que hagas algún endpoint de POST, como por ejemplo uno de eliminar o de actualizar alguna frase que ya haya en tu BBDD. Seguro que lo sacas sin problema!

En cualquier caso Unai, has buscado datos para incluir en tu API, los has almacenado en una BBDD de SQL creándote dos tablas, has creado distintos *endpoints* (tanto GET como POST) y has hecho una representación gráfica de algunos de tus resultados, muy buen trabajo, sigue asiiii 🔥🔥

![image](https://user-images.githubusercontent.com/75084991/117148454-83186800-adb6-11eb-9118-daff07715e80.png)
