### ISSUE TITLE
[W6-api-sentiment-project] Dario Contreras

### ISSUE THREAD

**Issue by DarioCMasedo** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#12]
https://github.com/DarioCMasedo/W6-api-sentiment-project

**Comment by AnaAGG** [comment]
# 🐺🔥 api-sentiment-project Darío 🐺🔥
Holaaaaa Darío 🙋‍♀️, vamos con el proyecto de crear una API!! 🔥🔥

## Readme
Vamos con el readme. En general muy buen trabajo, has explicado todos los *endpoints* de tu API y has incluido todas las librerías que has usado con los links a la documentación oficial 👏🏽. Te dejo por aquí algunos detalles que le pueden aportar valor a tu readme:

- Estaría bien que hicieras un pequeño resumen del objetivo tu proyecto, de que va, como lo has hecho, de donde has sacado los datos para hacer tu API...

- Sobre los endpoints, has indicado todos tus endpoints y lo que hace cada uno, podrías poner algun ejemplo de como hacer una petición. Por ejemplo:

        Some examples of API calls:
        To read all the phrases of a given character

        sentencias = ("http://0.0.0.0:5000/sentencias/IDPERSONAJE")

        Returns: 
        [{'sentencia': 'bla bla bla'},
        {'sentencia': 'bla bla bla'},
        {'sentecia': 'bla bla bla'}]


## Estructura del repositorio

En cuanto a la organización del repo, está super bien, tienes varias carpetas con contenido específico, muy bien Darío 👏🏽.  Peeero...

- Se te han colado algunos ficheros que tenían que ir al `.gitignore` como el `pycache`

- Tienes el archivo `configuration.py` lo tienes repetido dos veces, una dentro de la carpeta `config` y otro fuera. Ojo 👀 con eso!

Por el resto todo perfecto Darío!!! 🔥

## Sintaxis de código

- Genial que te hayas creado diferentes colecciones dentro de tu base de datos. 

- Me han faltado los *docstrings* en la funciones, recuerda, pueden ser suuper útiles para alguien de fuera que no sepa lo que hacen tus funciones y las pueda usar. 

- Suuuper bien que hayas incluido el análisis de sentimientos como un enpoint de tu API 🚀

- La función de *error handling* que te has creado esta peeerfectaaa, pero luego no la usas en ningún momento
    ```python
    def jsonErrorHandler(fn):
        def wrapper(*args, **kwargs):
            try:
                print("Calling fn")
                return fn(*args, **kwargs)
            except Exception as e:
                print(traceback.format_exc())
                return {
                    "error": str(e)
                }, 404
        return wrapper
    ```

- En las funciones del método `GET` tienes un par de funciones que podrías simplificar un poco (`sentencias` y `sentencia_episiodio`). Por ejemplo en la primera: 
    ```python
    # Todos las sentencias de un episodio
    # si lo que quieres es buscar todas las frases de un episodio sería tan fácil como buscar por un episodio dado. 

    def sentencia_episodio(id_episodio):
        return json_util.dumps(list(collection_sentencia.find({"_id": ObjectId("id_episodio")},{'Name':1,"Episode":1, "Sentence":1})))
    # Esta query te devolverá todas las frases del episodio 14 por ejemplo. 
    ```
- Puedes además meter un poco de *error handling en las funciones de get para que en caso de que si te pidan datos sobre un personaje/episodio/capítulo y no los tienes en tu BBDD les salga un mensaje

    ```python
     def sentencia_episodio(id_episodio):

         query = list(collection_sentencia.find({"_id": ObjectId("id_episodio")},{'Name':1,"Episode":1, "Sentence":1})))

         if len(query) = 0:
             return "sorry, we dont have this information
        else: 
            return json_util.dumps(list(collection_sentencia.find({"_id": ObjectId("id_episodio")},{'Name':1,"Episode":1, "Sentence":1})))
    
    ```

- Trabajas con los `id`, lo cual esta bien. Pero piensa que tu eres el generador de la base de datos, para el usuario los `id` pueden ser poco intuitivos, pero si puede ser más fácil poner el número del episodio 

Por el resto esta todo perfect, buen trabajo Darío!

## ToDo

Bueno Darío, en general hiciste muy buen trabajo, las APIs pueden ser un poco dolorosas al principio pero te has creado tu propia API 👏🏽 y se nota que lo has disfrutado. Te dejo por aquí algunas cosas que se me han ido ocurriendo segun leía tu proyecto 

- Puedes añadir algún método post más como actualizar alguna entrada o incluso eliminar alguna frase que el usuario sepa que esta mal.

- Puedes añadir un poco más de *error handling* en tus funciones. 


En cualquier caso Darío, te has descargado un *dataset*, lo has incorporado en una base de datos de mongo con múltiples colecciones, te has creado  *enpoints* (tanto GET como POST 👏🏽), has hecho una representación gráfica de tus datos y por último te has enfangado un poco con el html. Enhorabuena Darío, gran trabajo 💪! 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/118073955-47c8fb00-b3ad-11eb-9e13-ca0137fb62fc.png)
