### ISSUE TITLE
[W6-api-sentiment-project] Pablo Fernández Cañete

### ISSUE THREAD

**Issue by pfernancanete** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#14]
https://github.com/pfernancanete/W6-api-sentiment-project

No sé que problema he tenido con los endpoints.. nose porque sale error en el JN. El código está escrito pero no se conecta.. da error de numero de llamadas. ¿Me podeis ayudar a solucionarlo? Mil gracias !! :)

**Comment by breogann** [comment]
Pablo! 🙋🏻‍♂️

Más vale tarde que más tarde. Te cuento:

- Respecto a la **organización del repositorio 📚**
    - La distribución de los archivos en el repositorio está bien.
    - Tienes el .gitignore pero se te ha colado un archivo temporal de pycache (dentro de la carpeta de config). Para eliminar archivos temporales de github tendrías que hacer `git rm --cached arhivo`, luego añadir el archivo al gigitnore (puedes verlo en cualquier lab para añadirlo de forma recursiva), repetir el proceso de git add, commit y push.
- El **[README.md](http://readme.md/) ✍🏻**:
    - Recuerda que es súper importante, es lo que leerán los recruiters y en general cualquier persona que entre a tu repositorio. No te olvides de hacerlo!
- El **código 👩‍💻:**
    - Notebooks
        - Tweets:
            - Genial por haber comentado los pasos que sigues 👏👏
            - El código está bien: el manejo de pandas y apply, lambda, perfect.
            - Quizá separaría la parte de las queries en otro jupyter, para que tuviera una división más clara, pero tampoco es demasiado importante.
            - Parece que te falla porque: te da este error "ZeroDivisionError: division by zero", entonces imagino que, como antes haces la media, te ha querido coger el número total de valores pero se ha encontrado con que la lista estaba vacía, y su longitud es lo que utiliza para dividir. ¿mexplico? Básicamente que hacer la media de tres alumnos te da error si hay cero exámenes. Creo que puede ser por eso.
        - Polarity analysis:
            - Recuerda que los prints infinitos quedan así: [https://github.com/pfernancanete/W6-api-sentiment-project/blob/main/notebooks/02. Polarity Analysis.ipynb](https://github.com/pfernancanete/W6-api-sentiment-project/blob/main/notebooks/02.%20Polarity%20Analysis.ipynb) y hace difícil encontrar el código.
            - El que te salga todo ceros...podría pensar que es por el idioma, pero los tweets están en castellano...muchos de ellos son simplemente url (las fotos), pero el resto, no veo por qué te salen así.
        - API Calling:
            - El error de las llamadas no se te soluciona reestableciendo la conexión? tendría que ver tu local para poder debuggearlo.

En cualquier caso, la estructura del proyecto está bien, las funciones son sencillas, están bien parametrizadas y las importas bien entre archivos. También tienes las docstrings. Lo único que te faltaría sobre todo es el readme. Tienes la estructura, puedes escalar muy fácilmente el proyecto y añadir algo de visualiazación!

Dime si lo intentas debuggear y en qué se queda!

![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
