### ISSUE TITLE
[W6-api-sentiment-project] Antonio Pita

### ISSUE THREAD

**Issue by Antoniopita95** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#15]
https://github.com/Antoniopita95/W6-Api-sentiment-project

**Comment by breogann** [comment]
Antonio! 🙋🏻‍♂️

Más vale tarde que más tarde. Te cuento:

- Respecto a la **organización del repositorio 📚**
    - La distribución de los archivos en el repositorio está bien.
    - Se te ha colado el archivo .vscode. Tendrías que borrar el caché que ha guardado git de esa carpeta y meterlo en el gitignore. Luego repetir el proceso de add, commit y push.
- El **[README.md](http://readme.md/) ✍🏻**:
    - Recuerda que es súper importante, es lo que leerán los recruiters y en general cualquier persona que entre a tu repositorio.
- El **código 👩‍💻:**
    - Genial por tener el código comentado.  Cuidado con algunos docstrings, que parece que no te ha cogido bien los comentarios. Si te fijas, en algunos archivos tienes subrayada la palabra Function y from, como si te hubiera reconocido palabras reservadas. Es porque has puesto el docstring debajo del decorador, tendría que ir dentro del a función.
    - Las funciones que tienes están bien. Son sencillas, están bien importadas y  tiene lógica. Tienes un proyecto al que puedes añadir más cosas. Puedes añadir más endpoints y sobre todo, sacar insights: puedes sacar frecuencia y hacer alguna visualización o incluso añadir el sentiment analysis.

Por lo demás, parece que está bien. Ya sabes, como siempre le puedes meter más cosas. Lo que sí tienes que tener en cuenta es lo de esos docstrings, porque si no, no creo que se ejecute el archivo sin dar error.

Y el readmeeeeeee!

![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
