### ISSUE TITLE
[w6-api-sentiment-project] Cristina Callejo

### ISSUE THREAD

**Issue by CristinaCallejo** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#16]
[SAMS API](https://github.com/CristinaCallejo/SentimentAnalysis_MonarchSpeeches)

**Comment by AnaAGG** [comment]
# 🤴🏽👸🏽 api-sentiment-project 🤴🏽👸🏽
Holaaaaa Crissss 🙋‍♀️, vamos con el proyecto de crear una API!! 🔥🔥

## Readme

Vamos con el readme Cris! Empiezas con un pequeño resumen de los objetivos del proyecto y de lo que vas hacer, lo cual esta perfecto! Además has metido algunos ejemplos de tus endpoints 👏🏽. Te dejo por aquí algunos detalles que me han faltado y que te podrían aportar valor:

- Las librerias que has usado en este proyecto. Tienes los `requirements` (perfecto!), pero si de un vistazo el usuario puede verlas podría estar bien

- La construcción de una API puede ser un poco liosa ya que nos hacen falta muchos archivos y consta de muchos pasos. Un pequeño esquema o *workflow* de los pasos que has ido dando o los ficheros que hay en tu repo podrían ayudar. 

- Tienes otro archivo de markdown que se llama `reseach`, entiendo que en el futuro querrás meter info ahí sobre el proceso de trabajo , te animo a que le des ahí, puede ser muy interesante. 


## Estructura del repositorio

La organización del repo esta perfecta Cris, no tengo nada que decirte. Por destacar, te destacó dos puntos en esta parte:

- Genialllll no se te pasó ningún archivo temporal fuera del `.gitignore`

- Tienes todo el repo super compartimentado, con múltiples carpetas, donde en cada una de ellas guardas un ficheros con objetivos específicos. 

- En la carpeta `data visualizations` tienes dos ficheros en esa carpeta que no tienen que ver con el proyecto. Recuerda eliminarlos y meter las imagenes que te has creado en este proyecto. 

- Super bien que crearas el jupyter con algunos ejemplos de *requests* a tu API 👏🏽

Buen trabajo Cris, la estructura es esencial para tener un buen repo 🔝

## Sintaxis de código

Vamos con el código:

- **1_requests_scraping_for_data**
Genial que te hayas lanzado con el *scrapping* para sacar info para tu BBDD. 
El código del *scrapping* está perfecto pero se podría atomizar con distintas funciones. Por ejemplo: 
```python
# PARA escrapear el MUNDO el código es el mismo, lo que cambia es: la URL, la CLASE, NOMBRE de quien da el discurso y el AÑO. 
def get_mundo(*args, class_, name, year):
    for i in args:
    res = requests.get(url)
    soup = BeautifulSoup(res.content, 'html.parser')
    #print(soup3.prettify())
    scraping = soup.find("div",{"class":f"{class}"}).find_all("p")
    scrap = [i.get_text() for i in scraping]
    del scrap[:2]
    scrap_txt = "".join(scrap[2:])
    scrap.insert(0,f"{name}")
    scrap.insert(1,year)
    scrap.insert(2,scrap_txt)
    scrap = scrap[:3]
    return scrap
# de la misma forma te podrías crear una función para el diario de sevilla
def get_sevilla(url, class, name, year) :
    res = requests.get(url)
    soup = BeautifulSoup(res.content, 'html.parser')
    scraping = soup.find_all("p",{"class":f"{class}"})    scrap=[i.get_text() for i in scraping]
    del scrap[0]
    scrap_txt = "".join(scrap[2:])
    scrap.insert(0,f"{name}")
    scrap.insert(1,year)
    scrap.insert(2,scrap_txt)
    scrap = scrap[:3]
    return scrap
```

## ToDo

- Todas las funciones que tienes en el jupy del análisis de sentimientos las puedes pasar a un `.py` e importarlas en le jupy. 

- Te faltan los *docstrings* en las funciones. Dale duro hay, es muy importante para la gente que vaya a leer tu código saber que hace cada función y que parámetros recibe cada una.

- En los métodos `GET` puedes meter algún *endpoint* más, para buscar por monarca por ejemplo. 

- En los métodos `POST` también puedes añadir algunos más como por ejemplo eliminar alguna entrada o actualizar alguna que ya este incluida. 

Tienes unos resultados super molones!!Además tienes unos datos con muchísimo potencial, ya lo estuvimos charlando un día! Te ánimo a que trabajes cuando tengas tiempo en ello! 

En cualquier caso Cris, te has descargado un *dataset* usando *scrapeo*  🔝, lo has incorporado en una base de datos de Mongo, te has creado múltiples *enpoints* (tanto GET como POST) y por último has hecho una representación gráfica de tus datos. Enhorabuena Cris! 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/118391589-49a4ef80-b635-11eb-9540-65664303e56e.png)
