### ISSUE TITLE
[W6-api-sentiment-project] Edu Martínez

### ISSUE THREAD

**Issue by EduMartinezGarrido** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#17]
https://github.com/EduMartinezGarrido/API_SENTIMENT-GAME_OF_THRONES.git

**Comment by AnaAGG** [comment]
# 🐺🔥 api-sentiment-project 🐺🔥
Holaaaaa Eduuuuu 🙋‍♀️, vamos con el proyecto de crear una API!! 🔥🔥

## Readme

Super buen trabajo en el readme Edu 💪. Tienes varios ejemplos de tus endpoints, explicas los pasos que has seguido en el creación de tu API. Solo como recomendación:

- Cuando pones las librerías que has usado esta genial! Si ya pones los links a la documentación oficial te queda perfectoooo. 

## Estructura del repositorio
Buen trabajo con la estructura del repo Edu, lo tienes todo muy compartimentado 👏🏽. Te dejo por aquí un par de detalles por si te aportan valor: 

- Se te ha pasado algún fichero temporal fuera del `.gitignore`.

- Tienes un archivo `.ipynb` por ahí suelto, lo puedes meter en una carpeta a parte y quedaría suuper organizado todo. 

- Super bien ese jupyter con ejemplos de *request* a tu api. Y limitando los *outputs*!!!!!

- Todas las funciones con sus *docstrings* 👏🏽

## Sintaxis de código

Poco tengo que decirte de esta parte Edu, tienes el código muy organizado, con los docstrings. Solo como detalle:

- En el jupyter `main`, donde haces el análisis de sentimientos tienes unas cuantas funciones, en vez de tenerlas en el jupyter te las puedes llevar a un archivo `.py` y desde ahí exportarlas para que el jupy te quede limpito limpito. 
 

## ToDo

Bueno Edu, en general hiciste un buen trabajo, las APIs pueden ser un poco dolorosas al principio pero te has creado tu propia API 👏🏽. Te dejo por aquí algunas cosas que se me han ido ocurriendo segun leía tu proyecto 

- Puedes añadir algún método post más como actualizar alguna entrada o incluso eliminar alguna frase que el usuario sepa que esta mal.

- El análisis de sentimientos lo puedes incluir como un *endpoint* de tu API. Recuerda que podemos meter cualquier tipo de análisis como un enpoint en nuestra API. Puedes meter todas las funciones del análisis de sentimientos en un *enpoint* y luego que el usuario pida por ejemplo por temporada o personaje. 

En cualquier caso Edu, te has descargado un *dataset*, lo has incorparado en una base de datos de mongo, te has creado  *enpoints* (tanto GET como POST 👏🏽) y por último has hecho una representación gráfica de tus datos. Enhorabuena Edu! 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/118074117-98405880-b3ad-11eb-9917-dac8de4fdf39.png)
