### ISSUE TITLE
[W6-api-sentiment-project] Julieta Staryfurman

### ISSUE THREAD

**Issue by julistary** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#3]
https://github.com/julistary/W6-api-sentiment-project.git

**Comment by breogann** [comment]
Staryfurman! 🙋🏻‍♂️

Más vale tarde que más tarde. Te cuento:

- Respecto a la **organización del repositorio 📚**
    - Lo primero de todo: te lo dije en la presentación pero te lo comento igualmente por aquí. Recuerda mergear las carpetas de mongo_api y la de src. Podrías o bien tener los .py dentro de src o tener la carpeta misma dentro de src. Sí, es un jaleito de rutas, pero no tiene sentido tenerlo separado.
    - El .gitignore: estaba todo bien, hasta que: "mongo_api/.env". Con un .env en la root debería bastar, no tiene sentido tener duplicidad y/o tenerlo en una carpeta que no sea la root.
    - El `friends_json`  que tienes en la root? es pregunta. Lo mismo con  `script_friends_json`  y con `script` .  A priori, sin mirar el resto de archivos, no entiendo muy bien qué objetivo cumplen.
    - La carpeta de `dump/friends` (_rude_) puedes guardarla en la carpeta de data, ¿no? O bien tener una carpeta de input y otra de output.
    - Genial por el yml y el requirements.txt
- El **[README.md](http://readme.md/) ✍🏻**:
    - "The tools to be used are Flask, NLP, functions", ¿funciones?
    - Los to-do 👌
    - Por la parte de los endpoints, intenta poner los ejemplos de la forma más explícita que puedas. Es decir, pon incluso ejemplos con código de python: cómo hacer la request, cómo la devuelve, etc. No sólo el endpoint, sino con requests y todo.

        Vamos, intenta dejarlo como te gustaría encontrártelo. 

    - Por lo demás, está genial.
- El **código 👩‍💻:**
    - En la carpeta `src`:
        - data.py
            - Genial por los docstringssss
        - frequency.py
            - Para esta función:

            ```python
            def clean_script(whole_script):

                whole_script = whole_script.replace("[", "")
                whole_script = whole_script.replace("\\x92", "")
                whole_script = whole_script.replace("\"","")
                whole_script = whole_script.replace("'","")
                whole_script = whole_script.replace(",","")
                whole_script = whole_script.replace(".","")
                whole_script = whole_script.replace("!","")
                whole_script = whole_script.replace("?","")
                whole_script = whole_script.replace(")","")
                whole_script = whole_script.replace("(","")
                return whole_script
            ```

            podrías hacer un diccionario e iterar por los items para pasar todo. 

        - La lista de stopwords que sumas a la otra importada, ¿cómo la construyes?
        - Los import:

            ```python
            def times(main_characters):
                """
                Calls the Friends API and returns the number of times each character talks.
                Args:
                    main_characters (list): the list of the characters to work with
                Returns:
                    A dictionary with the number of quotes of each character
                """
                import re
            ```

            siempre al principio. ¿Te daba problemas?

        - Para esa misma función:

            ```python
            for c in main_characters:
                    person = c
                    nr_quotes = requests.get(url_times + person).content
            ```

            creas una variable que en realidad ya existe para referirte a ella más adelante con otro nombre? Piensa qué diría CleanMyMac de esto. Y por otro lado, piensa en que estas asignaciones tienen sentido cuando asignas una etiqueta/nombre a un valor, pero muchas veces podemos acabar estableciendo una relación de equivalencia entre dos valores, entonces se acaba sobre-escribiendo uno de ellos. Es decir, cuidado con eso porque puedes acabar haciendo 

            ```python
            3 = 5

            # y luego utilizar 3
            ```

            ¿me explico con esto? No sé si puede ser herencia de otros lenguajes.

        - Vale, he subido al principio del documento y estabas importando regex como "import regex", imagino que por eso te estaría dando problema.
    - Genial también por el  init.py!

    Por lo demás, el código de la parte de la API está genial: funciones sencillas que llaman a otras definidas en otro sitio. El código está documentado, tiene sentido y no es redundante. Sólo alguna cosilla que te comento .

    Has creado una base de datos, has creado enpdpoints de post, de get y has hecho un sentiment analysis.  A este proyecto siempre se le pueden añadir más cosas:  hacer más visualización, meter más datos, deploeyarlo, etc. En unas semanas habéis conseguido nutrir una base de datos a través de una aplicación vuestra y habéis sacado insights. 

    A tope Julieta!! 💪 🚀

    ![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
