### ISSUE TITLE
[ W6-api-sentiment-project] Emilio

### ISSUE THREAD

**Issue by emilio-carrasco** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#4]
https://github.com/emilio-carrasco/song-sentimental

**Comment by breogann** [comment]
Emilio! 🙋🏻‍♂️

Más vale tarde que más tarde. Te cuento:

- Respecto a la **organización del repositorio 📚**
    - Es cierto que no se te ha colado ningún archivo temporal, pero ten costumbre de tener un gitignore, pls.
    - La distribución de carpetas y de código está perfecta.
- El **[README.md](http://readme.md/) ✍🏻**:
    - En cuanto a la forma, puedes modificar alguna cosa del markdown: los títulos (con almohadillas) y los snippets de código.
    - Respecto al contenido: todobien. Para este proyecto puedes incluso poner ejemplos de cómo hacer una request con python. Cuanto más explícito, siempre mejor. Recuerda todas las API's que has visto y la documentación que tenían. Pero eso no quiere decir que no esté completo! Que tienes todos los endpoints y explicas todo lo que hace cada uno.
- El **código 👩‍💻:**
    - No conocía la librería de plataform 👏
    - Genial también por el __init __ (aunque en la carpeta de tools lo has escrito mal, te falta última letra)
    - Te faltan los docstrings en las funciones 🔪. Que entiendo que te diste cuenta por el nombre de este commit: "no sé si se han cargado comentarios de funciones".
    - Por lo demás, el código está muy bien.

    Puedes incluir un archivo yml por si quien lo clone quiere ejecutarlo con el entorno. Si no, el requirements.txt también está bien. 

![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
