### ISSUE TITLE
[W&-api-sentiment-project] Fran Leston

### ISSUE THREAD

**Issue by FranLeston** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#7]
[Flask NLP Server CHAT](https://github.com/FranLeston/nlp_chat)

**Comment by AnaAGG** [comment]
#  ☹️😀 api-sentiment-project ☹️😀
Holaaaaa Fran 🙋‍♀️, vamos con el proyecto de crear una API!!

## Readme
 
El readme está perfecto, empiezas explicando el objetivo del proyecto, como lo has hecho, tienes algunos ejemplos de tus endpoints y la estructura de tu BBDD en SQL 👏🏽. Te dejo por aquí algunos detalles por si te aportan valor:

- Esta genial que hayas puesto el fichero de los *requeriments* con todas las librerías que se usan en este repo. Podrías añadir al final una lista de las librerías que usaste con los links a la docu oficial. 

- Como te dijimos en la presentación del proyecto, la figura que tienes al final del readme puede ser algo compleja de entender *a priori*. La decisión de poner resultados en el readme es muy personal, que hayas puesto la gráfica está bien, pero si lo haces intenta meter una gráfica que sea un poco más auto-explicativa o pon en una línea algo que ayude a su interpretación. 

Por el resto muy buen trabajo. 

## Estructura del repositorio

En general muy buen trabajo con la estructura del repo Fran, esta todo muy bien compartimentado y estructurado. Solo por ponerme un poco tiquismiquis:

- Se te ha colado algún fichero temporal fuera del `.gitignore` como el `__pycache__`. 

- Tienes la carpeta de *images* dentro de la de *notebooks*. ¿Es por algo en particular? También la podrías sacar fuera de esta carpeta y que esté en la página principal de tu repo, que sean independientes los *notebooks* de las imágenes. 


## Sintaxis de código

 Lo gordo ya te lo comentamos cuando hiciste la presentación. Como te dijimos el proyecto en general esta perfecto, poco hay que decirte. Te dejo por aquí unos detalles por si te pueden ayudar en un futuro:

- Me han faltado los *docstrings* en las funciones
 
- En el *endpoint* del ver los resultados de un *user* en concreto trabajas con los `id`. Esto puede resultar sencillo para ti porque tu creaste la BBDD, pero un usuario no tiene por qué saber cuales son los `id` de la gente. Ni tendría  más sentido hacerlo por nombre y apellidos? Algo que sea más intuitivo. 

- Suuuper bien las funciones del archivo `nlp.py`, tienes creadas múltiples funciones las cuales se van llamando unas a otras hasta una final que las "engloba" a todas 👏🏽. 

## ToDo

Bueno Fran, muy muy buen trabajo, las APIs pueden ser un poco dolorosas al principio pero te has creado tu propia API 👏🏽. Te dejo por aquí algunas cosas que se me han ido ocurriendo según leía tu proyecto 

- Se podría añadir un *endpoint* para que un usuario dado tenga la capacidad de eliminar alguna frase que haya insertado en su BBDD. 

- Te quedaría si algunas de las gráficas que tienes en el jupyter las puedas meter en tu API a modo de resumen de los datos que tienes en tu BBDD. Gráficas como el `countplot` de los mensajes por su sentimiento son suuper ilustrativas

En cualquier caso Fran, te has creado tu BBDD en SQL, has creado dos tablas, te has creado  *enpoints* (tanto GET como POST 👏🏽), has hecho una representación gráfica de tus datos y por último la has *deployeado*. Enhorabuena Fran, gran trabajo 💪! 🔥🔥🔥

![image](https://user-images.githubusercontent.com/75084991/118095099-f54d0600-b3cf-11eb-81bc-a4621c33d55b.png)
