### ISSUE TITLE
[W6-api-sentiment-project]Carmen R

### ISSUE THREAD

**Issue by Carmen-r** [Ironhack-Data-Madrid-Marzo-2021/W6-api-sentiment-project#9]
https://github.com/Carmen-r/W6-api-sentiment-project.git

**Comment by breogann** [comment]
Carmen! 🙋🏻‍♂️

Más vale tarde que más tarde. Te cuento:

- Respecto a la **organización del repositorio 📚**
    - La distribución de carpetas y de código está perfecta. Lo único que, si quieres, puedes cambiar, es guardar la foto en una carpeta de jpg
    - El archivo de: vaccination_tweets_json lo puedes meter en data también
    - La carpeta de código fuente sería "src" en vez de "scr"
- El **[README.md](http://readme.md/) ✍🏻**:
    - Veo que tienes un montón de commits, lo cual está genial. Pero que muchos de ellos son para modificar el readme. Entiendo que porque los cambios que haces en local, hasta que no pusheas, no los ves, ¿no?

        Si es por eso, hay una extensión para el Visual Studio de markdown donde puedes tener una pantalla partida para visualizar le código tanto en markdwon como renderizado a la vez. Puedes mirar las extensiones con `cmmd + shift + x`

    - Tienes algunas erratas en el texto, ten cuidado con eso. Échale un ojo a grammarly, que te va corrigiendo según escribes. Recuerda que esto tiene que quedar a modo de portfolio de cara a un recruiter.
    - Por lo demás, las partes del readme están bien (aunque siempre puedes completarlo más añadiendo ejemplos de los endpoints)
- El **código 👩‍💻:**
    - En la carpeta `src`:
        - cleaning.py
            - La parte de las docstrings está súuper bien. La parte de importar regex dentro, ya tal. Pero es algo que os suele dar problemas, así que entiendo que lo haces a propósito para que te funcione.
        - sentimental.py
            - En esta función:

                ```python
                    text = re.sub(r'@\w+', '', text)
                    text = re.sub(r'#', '', text)
                    text = re.sub(r'RT[\s]+', '', text)
                    text = re.sub(r'https?:\/\/\S+', '', text)
                    text = text.lower()
                    return text
                ```

                podrías refactorizarlo y guardar los valores en un diccionario: {"patrón": "por lo que lo sustituyes"}. Y entonces simplemente hacer un map de pandas.

    - En la carpeta de tools:
        - Genial por el __init__.py
        - [getdaya.py](http://getdaya.py): 👌
        - postdata.py: 👌
    - mongoapi.py:
        - También genial. La idea era eso mismo, el que tuvieras poco código en ese archivo y las funciones estuvieran en otros archivos de código.

Los jupyters están de 10. Súper bien explicados. Me refiero por ejemplo a: "The polarity score is a float within the range [-1.0, 1.0], and it reflects the emotional charge of a statement or passage. Subjectivity is a float within the range [0.0, 1.0]"

Enhorabuena Carmen! Este proyecto está muy bien, la verdad que tienes muy poquitas cosas que cambiar. Alguna refactorización y algo del readme. Por lo demás, tienes buen código, está documentado y el repo está muy bien organizado. 

Te subiste bien en el cobete 🚀💪

![https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png](https://user-images.githubusercontent.com/54676992/108981112-b0e18200-768c-11eb-9525-e1166f10739b.png)
